# Generated by Django 4.0.6 on 2022-11-10 18:49

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', django_jalali.db.models.jDateTimeField()),
                ('end_time', django_jalali.db.models.jDateTimeField()),
                ('contract_time', django_jalali.db.models.jDateTimeField()),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
            ],
        ),
    ]
