# Generated by Django 4.0.6 on 2022-11-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0002_agent_alter_contract_contract_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercialname', models.CharField(max_length=50, verbose_name='نام تجاری')),
                ('brand', models.CharField(max_length=25, verbose_name='برند')),
                ('city', models.CharField(max_length=15, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن')),
                ('kind', models.CharField(choices=[('ordinary', 'عادی'), ('special', 'ویژه')], default='ordinary', max_length=8, verbose_name='نوع')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
            ],
        ),
    ]
