# Generated by Django 4.0.6 on 2022-11-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('active', 'فعال'), ('extending', 'در حال تمدید'), ('exp_30days', 'منقضی کمتر از 30 روز'), ('expired', 'منقضی')], default='active', max_length=25, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='brand',
            field=models.CharField(max_length=25, unique=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='commercialname',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام تجاری'),
        ),
    ]
