# Generated by Django 4.0.6 on 2022-12-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0005_alter_customer_kind_wireless_cloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('فنی', 'فنی'), ('بازرگانی', 'بازرگانی'), ('حقوقی', 'حقوقی')], default='tec', max_length=8, verbose_name='نقش نماینده'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('فعال', 'فعال'), ('در حال تمدید', 'در حال تمدید'), ('منقضی کمتر از 30 روز', 'منقضی کمتر از 30 روز'), ('منقضی', 'منقضی')], default='active', max_length=25, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='wireless',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.agent', verbose_name='نماینده'),
        ),
        migrations.AlterField(
            model_name='wireless',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.contract', verbose_name='قرارداد'),
        ),
        migrations.AlterField(
            model_name='wireless',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.customer', verbose_name='مشترک'),
        ),
    ]
