# Generated by Django 4.0.6 on 2022-12-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0006_alter_agent_role_alter_contract_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('فنی', 'فنی'), ('بازرگانی', 'بازرگانی'), ('حقوقی', 'حقوقی')], default='فنی', max_length=8, verbose_name='نقش نماینده'),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='size',
            field=models.CharField(choices=[('Micro', 'Micro'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XLarge', 'XLarge'), ('XXLarge', 'XXLarge')], default='Medium', max_length=7),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('فعال', 'فعال'), ('در حال تمدید', 'در حال تمدید'), ('منقضی کمتر از 30 روز', 'منقضی کمتر از 30 روز'), ('منقضی', 'منقضی')], default='فعال', max_length=25, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='wireless',
            name='popsite',
            field=models.CharField(choices=[('بوتان', 'بوتان'), ('شریعتی', 'شریعتی'), ('زرین', 'زرین'), ('کردستان', 'کردستان'), ('سنایی', 'سنایی'), ('پلاستیران', 'پلاستیران')], default='فعال', max_length=25, verbose_name='پاپ سایت'),
        ),
    ]
