# Generated by Django 4.0.6 on 2022-12-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0007_alter_agent_role_alter_cloud_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireless',
            name='popsite',
            field=models.CharField(choices=[('بوتان', 'بوتان'), ('شریعتی', 'شریعتی'), ('زرین', 'زرین'), ('کردستان', 'کردستان'), ('سنایی', 'سنایی'), ('پلاستیران', 'پلاستیران')], default='بوتان', max_length=25, verbose_name='پاپ سایت'),
        ),
    ]
