# Generated by Django 4.0.6 on 2022-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0008_alter_wireless_popsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('فعال', 'فعال'), ('در حال تمدید', 'در حال تمدید'), ('پیش نویس', 'پیش نویس'), ('منقضی کمتر از 30 روز', 'منقضی کمتر از 30 روز'), ('منقضی', 'منقضی')], default='فعال', max_length=25, verbose_name='وضعیت'),
        ),
    ]
