# Generated by Django 4.0.6 on 2023-02-14 09:52

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0009_alter_contract_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='cloud',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wireless',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='wireless',
            name='prefix',
            field=models.PositiveSmallIntegerField(blank=True, default=29, null=True, verbose_name='ُPrefix'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_time',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ انعقاد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_time',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_time',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='wireless',
            name='ip',
            field=models.GenericIPAddressField(error_messages={'required': 'پرش کن!'}, verbose_name='آدرس IP'),
        ),
        migrations.AlterField(
            model_name='wireless',
            name='popsite',
            field=models.CharField(choices=[('بوتان', 'بوتان'), ('شریعتی', 'شریعتی'), ('زرین', 'زرین'), ('کردستان', 'کردستان'), ('سنایی', 'سنایی'), ('پلاستیران', 'پلاستیران')], default='بوتان', help_text='اسم پاپ سایت', max_length=25, verbose_name='پاپ سایت'),
        ),
        migrations.AlterField(
            model_name='wireless',
            name='throughput_r_bw',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='پهنای باند دریافت نقطه به نقطه'),
        ),
    ]
