# Generated by Django 4.0.6 on 2023-03-31 19:24

import customerservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0010_alter_agent_options_alter_cloud_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_ip', models.BooleanField()),
                ('ip1', models.GenericIPAddressField(verbose_name='IP1')),
                ('subnet_mask1', models.PositiveSmallIntegerField(verbose_name='Subnet Mask1')),
                ('ip2', models.GenericIPAddressField(verbose_name='IP2')),
                ('subnet_mask2', models.PositiveSmallIntegerField(verbose_name='Subnet Mask2')),
                ('ip3', models.GenericIPAddressField(verbose_name='IP3')),
                ('subnet_mask3', models.PositiveSmallIntegerField(verbose_name='Subnet Mask3')),
                ('ip4', models.GenericIPAddressField(verbose_name='IP4')),
                ('subnet_mask4', models.PositiveSmallIntegerField(verbose_name='Subnet Mask4')),
                ('ip5', models.GenericIPAddressField(verbose_name='IP5')),
                ('subnet_mask5', models.PositiveSmallIntegerField(verbose_name='Subnet Mask5')),
                ('ip6', models.GenericIPAddressField(verbose_name='IP6')),
                ('subnet_mask6', models.PositiveSmallIntegerField(verbose_name='Subnet Mask6')),
                ('ip7', models.GenericIPAddressField(verbose_name='IP7')),
                ('subnet_mask7', models.PositiveSmallIntegerField(verbose_name='Subnet Mask7')),
                ('ip8', models.GenericIPAddressField(verbose_name='IP8')),
                ('subnet_mask8', models.PositiveSmallIntegerField(verbose_name='Subnet Mask8')),
                ('ip9', models.GenericIPAddressField(verbose_name='IP9')),
                ('subnet_mask9', models.PositiveSmallIntegerField(verbose_name='Subnet Mask9')),
                ('IP10', models.GenericIPAddressField(verbose_name='IP10')),
                ('subnet_mask10', models.PositiveSmallIntegerField(verbose_name='Subnet Mask10')),
                ('first_vlan', models.PositiveSmallIntegerField(verbose_name='first_vlan')),
                ('router_first_vlan', models.CharField(max_length=15, verbose_name='router_first_vlan')),
                ('second_vlan', models.PositiveSmallIntegerField(verbose_name='second_vlan')),
                ('router_second_vlan', models.CharField(max_length=15, verbose_name='router_second_vlan')),
                ('third_vlan', models.PositiveSmallIntegerField(verbose_name='third_vlan')),
                ('router_third_vlan', models.CharField(max_length=15, verbose_name='router_third_vlan')),
                ('forth_vlan', models.PositiveSmallIntegerField(verbose_name='forth_vlan')),
                ('router_forth_vlan', models.CharField(max_length=15, verbose_name='router_forth_vlan')),
                ('fifth_vlan', models.PositiveSmallIntegerField(verbose_name='fifth_vlan')),
                ('router_fifth_vlan', models.CharField(max_length=15, verbose_name='router_fifth_vlan')),
                ('transmission', models.CharField(max_length=500, verbose_name='transmission')),
            ],
        ),
        migrations.AlterField(
            model_name='wireless',
            name='prefix',
            field=models.PositiveSmallIntegerField(blank=True, default=29, null=True, validators=[customerservice.models.ip_test], verbose_name='ُPrefix'),
        ),
    ]
