# Generated by Django 4.0.6 on 2023-04-05 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0011_othersevices_alter_wireless_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.customer')),
            ],
        ),
    ]
