# Generated by Django 4.0.6 on 2023-04-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0012_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP1')),
                ('dev_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='نام تجهیز')),
                ('dev_rack', models.CharField(blank=True, max_length=5, null=True, verbose_name='شماره رک')),
                ('dev_scale', models.CharField(choices=[('اقتصادی', 'اقتصادی'), ('استاندارد', 'استاندارد'), ('پیشرفته', 'پیشرفته'), ('سازمانی', 'سازمانی'), ('سازمانی ویژه', 'سازمانی ویژه'), ('G10-سازمانی', 'G10-سازمانی'), ('G10-سازمانی ویژه', 'G10-سازمانی ویژه')], default='اقتصادی', max_length=20, verbose_name='مقیاس تجهیز')),
                ('dev_dc', models.CharField(choices=[('سهند ط 2', 'سهند ط 2'), ('سهند ط 3', 'سهند ط 3'), ('سهند ط 5', 'سهند ط 5'), ('شاهین همکف', 'شاهین همکف'), ('شاهین زیرزمین', 'شاهین زیرزمین'), ('بهشتی', 'بهشتی'), ('رمضانی', 'رمضانی')], default='اقتصادی', max_length=13, verbose_name='مقیاس تجهیز')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.agent')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Colocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_brand', models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('Cisco', 'Cisco'), ('MikroTik', 'MikroTik'), ('EMC', 'EMC'), ('Other', 'Other')], default='HP', max_length=8, verbose_name='برند تجهیز')),
                ('dev_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='نام تجهیز')),
                ('dev_rack', models.CharField(blank=True, max_length=5, null=True, verbose_name='شماره رک')),
                ('dev_scale', models.CharField(choices=[('اقتصادی', 'اقتصادی'), ('استاندارد', 'استاندارد'), ('پیشرفته', 'پیشرفته')], default='اقتصادی', max_length=9, verbose_name='مقیاس تجهیز')),
                ('dev_dc', models.CharField(choices=[('سهند ط 2', 'سهند ط 2'), ('سهند ط 3', 'سهند ط 3'), ('سهند ط 5', 'سهند ط 5'), ('شاهین همکف', 'شاهین همکف'), ('شاهین زیرزمین', 'شاهین زیرزمین'), ('بهشتی', 'بهشتی'), ('رمضانی', 'رمضانی')], default='اقتصادی', max_length=13, verbose_name='مقیاس تجهیز')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.agent')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('subnet_mask', models.PositiveSmallIntegerField(blank=True, default=29, null=True, verbose_name='ُsubnet_mask')),
                ('vlan', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='vlan')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.agent')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Mpls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('subnet_mask', models.PositiveSmallIntegerField(blank=True, default=29, null=True, verbose_name='ُsubnet_mask')),
                ('vlan', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='vlan')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.agent')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
